spring:
  datasource:
    url: jdbc:mysql://tddatabase.c1dwqgiixd1c.ap-northeast-2.rds.amazonaws.com/tb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 19288291
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    host: localhost
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: todayisdiary@gmail.com
    password: bqvkgnlqnylifktp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jwt:
    key: asdkhfqwioehraskjldbfklasbdfiuasdufweyhrjkahskldfhasduhfkljasdbhnfkjbaslkdfbuabsdufhiouhyweuiorhkljasdhflkusadhfkjbasdlkfbuashfkasbdlkfjh
    live:
      atk: 3600000
      rtk: 604800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

cloud:
  aws:
    credentials:
      accessKey: AKIAWUTT3RNCWRQ5ZASA
      secretKey: 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
    s3:
      bucket: td-project-bucket
      dir: image
    region:
      static: ap-northeast-2
    stack:
      auto: false
